### ISSUE TITLE
Trying to contact

### ISSUE THREAD

**Issue by SamJaphia** [pothonprogramming/pothonprogramming.github.io#1]
Hi mate,

Been trying to contact you, I love your vids and been using them to learn.

I have a question to ask about a project I am building, looking forward to hearing from you soon.

Kind regards,

Sam

**Comment by pothonprogramming** [comment]
I need to get my Discord set up properly. Try this handle: pothonprogramming#8141. If that doesn't work, I will be officially setting up Discord and putting the contact info out here: https://www.youtube.com/c/PothOnProgramming/about

Also, feel free to comment on the videos if it's nothing too complex. I check YouTube more often than Discord and I am no longer active on other social platforms due to time constraints, but I am in the process of reorganizing my schedule to make more time for the channel, and that includes Discord.

**Comment by omiinaya** [comment]
hey fam, i sent you a friend request as well. been playing around with your tutorials and learning a lot but i have a couple questions if you find the time. thanks in advance.

**Comment by pothonprogramming** [comment]
I'm going to close this issue. If you would like to contact me, drop a comment on the YouTube channel or hit me up on Discord. If you go to https://pothonprogramming.github.io you can find the link to join the discord at the top.
